const layout = {
  en: [
    { keyCode: 'Backquote', key: '`', shiftVal: '~' },
    { keyCode: 'Digit1', key: '1', shiftVal: '!' },
    { keyCode: 'Digit2', key: '2', shiftVal: '@' },
    { keyCode: 'Digit3', key: '3', shiftVal: '#' },
    { keyCode: 'Digit4', key: '4', shiftVal: '$' },
    { keyCode: 'Digit5', key: '5', shiftVal: '%' },
    { keyCode: 'Digit6', key: '6', shiftVal: '^' },
    { keyCode: 'Digit7', key: '7', shiftVal: '&' },
    { keyCode: 'Digit8', key: '8', shiftVal: '*' },
    { keyCode: 'Digit9', key: '9', shiftVal: '(' },
    { keyCode: 'Digit0', key: '0', shiftVal: ')' },
    { keyCode: 'Minus', key: '-', shiftVal: '_' },
    { keyCode: 'Equal', key: '=', shiftVal: '+' },
    { keyCode: 'Backspace', key: 'back', shiftVal: null },
    { keyCode: 'Tab', key: 'tab', shiftVal: '' },
    { keyCode: 'KeyQ', key: 'q', shiftVal: 'Q' },
    { keyCode: 'KeyW', key: 'w', shiftVal: 'W' },
    { keyCode: 'KeyE', key: 'e', shiftVal: 'E' },
    { keyCode: 'KeyR', key: 'r', shiftVal: 'R' },
    { keyCode: 'KeyT', key: 't', shiftVal: 'T' },
    { keyCode: 'KeyY', key: 'y', shiftVal: 'Y' },
    { keyCode: 'KeyU', key: 'u', shiftVal: 'U' },
    { keyCode: 'KeyI', key: 'i', shiftVal: 'I' },
    { keyCode: 'KeyO', key: 'o', shiftVal: 'O' },
    { keyCode: 'KeyP', key: 'p', shiftVal: 'P' },
    { keyCode: 'BracketLeft', key: '[', shiftVal: '{' },
    { keyCode: 'BracketRight', key: ']', shiftVal: '}' },
    { keyCode: 'Backslash', key: '\\', shiftVal: ' | ' },
    { keyCode: 'Delete', key: 'del', shiftVal: null },
    { keyCode: 'CapsLock', key: 'caps lock', shiftVal: null },
    { keyCode: 'KeyA', key: 'a', shiftVal: 'A' },
    { keyCode: 'KeyS', key: 's', shiftVal: 'S' },
    { keyCode: 'KeyD', key: 'd', shiftVal: 'D' },
    { keyCode: 'KeyF', key: 'f', shiftVal: 'F' },
    { keyCode: 'KeyG', key: 'g', shiftVal: 'G' },
    { keyCode: 'KeyH', key: 'h', shiftVal: 'H' },
    { keyCode: 'KeyJ', key: 'j', shiftVal: 'J' },
    { keyCode: 'KeyK', key: 'k', shiftVal: 'K' },
    { keyCode: 'KeyL', key: 'l', shiftVal: 'L' },
    { keyCode: 'Semicolon', key: ';', shiftVal: ':' },
    { keyCode: 'Quote', key: null, shiftVal: '"' },
    { keyCode: 'Enter', key: 'enter', shiftVal: null },
    { keyCode: 'ShiftLeft', key: 'shift', shiftVal: null },
    { keyCode: 'KeyZ', key: 'z', shiftVal: 'Z' },
    { keyCode: 'KeyX', key: 'x', shiftVal: 'X' },
    { keyCode: 'KeyC', key: 'c', shiftVal: 'C' },
    { keyCode: 'KeyV', key: 'v', shiftVal: 'V' },
    { keyCode: 'KeyB', key: 'b', shiftVal: 'B' },
    { keyCode: 'KeyN', key: 'n', shiftVal: 'N' },
    { keyCode: 'KeyM', key: 'm', shiftVal: 'M' },
    { keyCode: 'Comma', key: ',', shiftVal: '<' },
    { keyCode: 'Period', key: '.', shiftVal: '>' },
    { keyCode: 'Slash', key: '/', shiftVal: '?' },
    { keyCode: 'ArrowUp', key: '▲', shiftVal: '' },
    { keyCode: 'ShiftRight', key: 'shift', shiftVal: null },
    { keyCode: 'ControlLeft', key: 'ctrl', shiftVal: null },
    { keyCode: 'MetaLeft', key: 'start', shiftVal: null },
    { keyCode: 'AltLeft', key: 'alt', shiftVal: null },
    { keyCode: 'Space', key: ' ', shiftVal: ' ' },
    { keyCode: 'AltRight', key: 'alt', shiftVal: null },
    { keyCode: 'ControlRight', key: 'ctrl', shiftVal: null },
    { keyCode: 'ArrowLeft', key: '◀', shiftVal: null },
    { keyCode: 'ArrowDown', key: '▼', shiftVal: null },
    { keyCode: 'ArrowRight', key: '▶', shiftVal: null },
  ],
  ka: [
    { keyCode: 'Backquote', key: '`', shiftVal: '~' },
    { keyCode: 'Digit1', key: '1', shiftVal: '!' },
    { keyCode: 'Digit2', key: '2', shiftVal: '@' },
    { keyCode: 'Digit3', key: '3', shiftVal: '#' },
    { keyCode: 'Digit4', key: '4', shiftVal: '$' },
    { keyCode: 'Digit5', key: '5', shiftVal: '%' },
    { keyCode: 'Digit6', key: '6', shiftVal: '^' },
    { keyCode: 'Digit7', key: '7', shiftVal: '&' },
    { keyCode: 'Digit8', key: '8', shiftVal: '*' },
    { keyCode: 'Digit9', key: '9', shiftVal: '(' },
    { keyCode: 'Digit0', key: '0', shiftVal: ')' },
    { keyCode: 'Minus', key: '-', shiftVal: '_' },
    { keyCode: 'Equal', key: '=', shiftVal: '+' },
    { keyCode: 'Backspace', key: 'back', shiftVal: null },
    { keyCode: 'Tab', key: 'tab', shiftVal: '' },
    { keyCode: 'KeyQ', key: 'ქ', shiftVal: 'ქ' },
    { keyCode: 'KeyW', key: 'წ', shiftVal: 'ჭ' },
    { keyCode: 'KeyE', key: 'ე', shiftVal: 'ე' },
    { keyCode: 'KeyR', key: 'რ', shiftVal: 'ღ' },
    { keyCode: 'KeyT', key: 'ტ', shiftVal: 'თ' },
    { keyCode: 'KeyY', key: 'ყ', shiftVal: 'ყ' },
    { keyCode: 'KeyU', key: 'უ', shiftVal: 'უ' },
    { keyCode: 'KeyI', key: 'ი', shiftVal: 'ი' },
    { keyCode: 'KeyO', key: 'ო', shiftVal: 'ო' },
    { keyCode: 'KeyP', key: 'პ', shiftVal: 'პ' },
    { keyCode: 'BracketLeft', key: '[', shiftVal: '{' },
    { keyCode: 'BracketRight', key: ']', shiftVal: '}' },
    { keyCode: 'Backslash', key: '\\', shiftVal: ' | ' },
    { keyCode: 'Delete', key: 'del', shiftVal: null },
    { keyCode: 'CapsLock', key: 'caps lock', shiftVal: null },
    { keyCode: 'KeyA', key: 'ა', shiftVal: 'ა' },
    { keyCode: 'KeyS', key: 'ს', shiftVal: 'შ' },
    { keyCode: 'KeyD', key: 'დ', shiftVal: 'დ' },
    { keyCode: 'KeyF', key: 'ფ', shiftVal: 'ფ' },
    { keyCode: 'KeyG', key: 'გ', shiftVal: 'გ' },
    { keyCode: 'KeyH', key: 'ჰ', shiftVal: 'ჰ' },
    { keyCode: 'KeyJ', key: 'ჯ', shiftVal: 'ჟ' },
    { keyCode: 'KeyK', key: 'კ', shiftVal: 'კ' },
    { keyCode: 'KeyL', key: 'ლ', shiftVal: 'ლ' },
    { keyCode: 'Semicolon', key: ';', shiftVal: ':' },
    { keyCode: 'Quote', key: null, shiftVal: '"' },
    { keyCode: 'Enter', key: 'enter', shiftVal: null },
    { keyCode: 'ShiftLeft', key: 'shift', shiftVal: '' },
    { keyCode: 'KeyZ', key: 'ზ', shiftVal: 'ძ' },
    { keyCode: 'KeyX', key: 'ხ', shiftVal: 'ხ' },
    { keyCode: 'KeyC', key: 'ც', shiftVal: 'ჩ' },
    { keyCode: 'KeyV', key: 'ვ', shiftVal: 'ვ' },
    { keyCode: 'KeyB', key: 'ბ', shiftVal: 'ბ' },
    { keyCode: 'KeyN', key: 'ნ', shiftVal: 'ნ' },
    { keyCode: 'KeyM', key: 'მ', shiftVal: 'მ' },
    { keyCode: 'Comma', key: ',', shiftVal: '<' },
    { keyCode: 'Period', key: '.', shiftVal: '>' },
    { keyCode: 'Slash', key: '/', shiftVal: '?' },
    { keyCode: 'ArrowUp', key: '▲', shiftVal: '' },
    { keyCode: 'ShiftRight', key: 'shift', shiftVal: '' },
    { keyCode: 'ControlLeft', key: 'ctrl', shiftVal: '' },
    { keyCode: 'MetaLeft', key: 'start', shiftVal: '' },
    { keyCode: 'AltLeft', key: 'alt', shiftVal: '' },
    { keyCode: 'Space', key: ' ', shiftVal: null },
    { keyCode: 'AltRight', key: 'alt', shiftVal: null },
    { keyCode: 'ControlRight', key: 'ctrl', shiftVal: null },
    { keyCode: 'ArrowLeft', key: '◀', shiftVal: null },
    { keyCode: 'ArrowDown', key: '▼', shiftVal: null },
    { keyCode: 'ArrowRight', key: '▶', shiftVal: null },
  ],
};

export default layout;
